---
- name: Copy v4 save script
  template: src=save.v4.j2 dest=/etc/network/if-post-down.d/iptables-v4 owner=root group=root mode=755

- name: Copy v4 restore script
  template: src=restore.v4.j2 dest=/etc/network/if-pre-up.d/iptables-v4 owner=root group=root mode=755

- name: ensure ufw is installed
  apt:
    name: ufw
    state: latest

- name: Drop incoming connections
  ufw:
    direction: incoming
    policy: deny

- name: Enable firewall rule to limit incoming ssh trafic
  ufw:
    rule: limit
    port: ssh
    proto: tcp
    state: enabled
